title: Scribbles And Marginalia
description: A blogging website focusing on literature and paratext.
header_text: Notes in the Margins
footer_text: Copyright 2020
header_feature_image: ../uploads/pages.jpg
bannerheight: 20vmax
logo: ../uploads/artboard-1-100.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
