title: Dragon & Magpie Books
description: A blogging website focusing on literature and paratext.
header_text: Dragon & Magpie Books
footer_text: Copyright 2020 Dragon & Magpie
header_feature_image: ../uploads/pages.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
